name: Page Object Model
on: [push]
jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install
        run: npm install
      - name: Test
        run: npm run wdio
      - uses: actions/upload-artifact@v1
        with:
          name: Allure Report
          path: ./Page-Object_Model/allure-results